name: HYSPLIT-Q
channels:
  - conda-forge
dependencies:
  # Enforce Python version
  - python=3.12

  # Scientific python
  - jupyterlab
  - networkx
  - numpy
  - openpyxl
  - pandas
  - scipy
  - xarray
  - netcdf4
  - h5py
  - dask
  - argparse
  - kneed
  - pathlib
  - re
  - typing
  - sys

  # Plotting
  - ipympl
  - matplotlib-base
  - plotly
  - seaborn

  # Machine learning
  - scikit-learn

  # General chemistry
  - ase
  - mendeleev
  - mordred
  - rdkit

  # Materials Project
  - mp-api
  - pymatgen

  # Utilities
  - pycodestyle
  - ruff

  # Install some things through pip
  - pip
  # - pip:
  #   - mpcontribs-client
